### ISSUE TITLE
Error: object reference not set to an instance

### ISSUE THREAD

**Issue by unimasacid** [wangyw15/CeVIO_Crack#3]
After run the activator, it comes up with an error saying "object reference not set to an instance".
Using the latest activator 2.1, re-installed cevio for times and also older versions, still not work

**Comment by wangyw15** [comment]
What's the version of cevio?

**Comment by wangyw15** [comment]
I'm currently using 9.1.16.0, everything works fine.

When re-installing cevio, manually delete files in the installation folder, then go on with installation.

If that not helped, please describe what you have done and post the log for me to reproduce the problem :)

**Comment by unimasacid** [comment]
unfortunately it didnt help, the problem remains
here is the log about the problem

===================================

[CLR] 4.0.30319.42000 on .NET Framework 4.8.09037 (Release: 533325)
[Application] 9.1.16.0

Object reference not set to an instance of an object.

...[Stack Trace]
   at CeVIO.Editor.Data.UnitGroup..ctor(UnitCategory category)
   at CeVIO.Editor.Adapters.SceneCircuit.AddGroup(UnitCategory category, String castId, UnitGroupCircuit baseGroup, Boolean belowBase)
   at CeVIO.Editor.Adapters.SceneCircuit..ctor(Scene data)
   at CeVIO.Editor.Adapters.SequenceCircuit.Initialize(Sequence data)
   at CeVIO.Editor.Adapters.MainWindowCircuit.<OnGotReady>b__580_0()


[Stack Trace]
   at CeVIO.Editor.Data.UnitGroup..ctor(UnitCategory category)
   at CeVIO.Editor.Adapters.SceneCircuit.AddGroup(UnitCategory category, String castId, UnitGroupCircuit baseGroup, Boolean belowBase)
   at CeVIO.Editor.Adapters.SceneCircuit..ctor(Scene data)
   at CeVIO.Editor.Adapters.SequenceCircuit.Initialize(Sequence data)
   at CeVIO.Editor.Adapters.MainWindowCircuit.<OnGotReady>b__580_0()

**Comment by wangyw15** [comment]
What have you done before the patch?

**Comment by wangyw15** [comment]
Have you installed any voicebanks?

**Comment by unimasacid** [comment]
I havent installed any voicebank yet
I just installed cevio, ran the activator, then the error occurs
maybe i should install at least one voicebank first?

**Comment by unimasacid** [comment]
I did a re-installation again, and this time with SEKAI voicebank
then i ran the activator, the error remains there

**Comment by wangyw15** [comment]
that's weird. by the way, have u post the problem on the tieba? that one has the same problem with u.

**Comment by wangyw15** [comment]
try delete the registry `HKEY_CURRENT_USER\Software\CeVIO_NV` and start the cevio again?

**Comment by wangyw15** [comment]
currently i cant reproduce the problem, just provide ways trying to solve the problem🥲

**Comment by unimasacid** [comment]
no, i only post the issue here
i tried delete the registry but still not work
what could the reason be? is it about the envionment or software conflict?

**Comment by wangyw15** [comment]
since the problem  is reported twice, there might be some bug in the activator

i will try the patch in a virtual machine.

**Comment by wangyw15** [comment]
i've reproduced in virtual machine, now i can try to solve it😊

**Comment by wangyw15** [comment]
oh, i figured out why.

the patch activates both song and talk by default, so cevio will look for voicebanks. if u only install song but not talk, it will crash and vice versa.

to solve it, install at least one voicebank both for talk and song

**Comment by wangyw15** [comment]
later i will try to add logic to activate based on installed voicebanks.

**Comment by wangyw15** [comment]
rename `CeVIO AI.exe.bak` to `CeVIO AI.exe` and try [v2.2](https://github.com/wangyw15/CeVIOActivator/releases/tag/v2.2), that should be ok

**Comment by unimasacid** [comment]
thank a lot, it works!!!
thanks so much for your quick response
