### ISSUE TITLE
No exe file

### ISSUE THREAD

**Issue by OdinBUTuhhhhhhh** [wangyw15/CeVIO_Crack#4]
I downloaded the only downloadable files in releases, and there is no exe file.
![no exe](https://github.com/user-attachments/assets/9e7976ed-4e47-45b0-bdbc-75d2655bc746)

**Comment by wangyw15** [comment]
I forgot to upload it :P

I will upload it later.

You can try previous versions.

**Comment by wangyw15** [comment]
Upload exe file.
